[build]
  publish = "./public"
  command = "mkdir -p ./public && curl -L https://github.com/Saad-Naseer/MediaAI-web/raw/main/model/model.tar.gz -o ./public/model.tar.gz"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"