
[build]
  publish = "."
  command = "mkdir -p ./model && curl -L https://github.com/Saad-Naseer/MediaAI-web/raw/main/model/model.tar.gz -o ./model/model.tar.gz"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"